/*
 * OpenAPI bitcoin service
 *
 * This is the OpenAPI definition of the bitcoin service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"context"
	"errors"
	"net/http"

	"github.com/CHainGate/bitcoin-service/openApi"
)

// NotificationApiService is a service that implements the logic for the NotificationApiServicer
// This service should implement the business logic for every endpoint for the NotificationApi API.
// Include any external packages or services that will be required by this service.
type NotificationApiService struct {
}

// NewNotificationApiService creates a default api service
func NewNotificationApiService() openApi.NotificationApiServicer {
	return &NotificationApiService{}
}

// BlockNotify - New block notification from bitcoin node
func (s *NotificationApiService) BlockNotify(ctx context.Context, blockNotifyRequestDto openApi.BlockNotifyRequestDto) (openApi.ImplResponse, error) {
	//TODO: free used accounts if no payment received after maybe 1h??

	return openApi.Response(http.StatusNotImplemented, nil), errors.New("BlockNotify method not implemented")
}

// WalletNotify - New wallet notification from Bitcoin Node
func (s *NotificationApiService) WalletNotify(ctx context.Context, walletNotifyRequestDto openApi.WalletNotifyRequestDto) (openApi.ImplResponse, error) {

	return openApi.Response(http.StatusNotImplemented, nil), errors.New("WalletNotify method not implemented")
}
