/*
 * OpenAPI bitcoin service
 *
 * This is the OpenAPI definition of the bitcoin service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"context"
	"net/http"

	"github.com/CHainGate/bitcoin-service/openApi"
)

// PaymentApiService is a service that implements the logic for the PaymentApiServicer
// This service should implement the business logic for every endpoint for the PaymentApi API.
// Include any external packages or services that will be required by this service.
type PaymentApiService struct {
	bitcoinService IBitcoinService
}

// NewPaymentApiService creates a default api service
func NewPaymentApiService(bitcoinService IBitcoinService) openApi.PaymentApiServicer {
	return &PaymentApiService{bitcoinService}
}

// CreatePayment - create new payment
func (s *PaymentApiService) CreatePayment(ctx context.Context, paymentRequestDto openApi.PaymentRequestDto) (openApi.ImplResponse, error) {
	payment, err := s.bitcoinService.createNewPayment(paymentRequestDto)
	if err != nil {
		return openApi.Response(http.StatusBadRequest, payment), err
	}

	return openApi.Response(http.StatusCreated, payment), nil
}
