version: '3'
services:
  network:
    build: ""
    ports:
      - "18400:18443"
      - "18500:18444"
    expose:
      - "18444"
    command: ["-dustrelayfee=0.0"]
  buyer:
    build: ""
    ports:
      - "18401:18443"
      - "18501:18444"
    expose:
      - "18444"
    command: ["-addnode=network:18443"]
  merchant:
    build: ""
    ports:
      - "18402:18443"
      - "18502:18444"
    expose:
      - "18444"
    command: ["-addnode=network:18443"]
  chaingate:
    build: ""
    ports:
      - "18403:18443"
      - "18503:18444"
    expose:
      - "18444"
    command: ["-addnode=network:18443", "-walletnotify=curl 'host.docker.internal:9001/api/notification/walletnotify?tx_id=%s&mode=test'", "-blocknotify=curl 'host.docker.internal:9001/api/notification/blocknotify?block_hash=%s&mode=test'"]